# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uOAyTMASp2GdnHwG-CkbbuHRpEsm-7se
"""

pip install -q transformers accelerate torch gradio gtts pydub

import gradio as gr
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from gtts import gTTS
import os
from datetime import datetime
import tempfile

# ========================================
# 1. INITIALIZE IBM GRANITE MODEL
# ========================================
print("🔄 Loading IBM Granite 3.3 2B Instruct model...")

model_name = "ibm-granite/granite-3.1-2b-instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto"
)

print("✅ Model loaded successfully!")

# ========================================
# 2. TONE REWRITING FUNCTION
# ========================================
def rewrite_text(original_text, tone):
    """Rewrites text in the specified tone using IBM Granite LLM"""

    tone_prompts = {
        "Neutral": "Rewrite the following text in a clear, neutral, and objective tone. Maintain all key information but make it sound balanced and factual:",
        "Suspenseful": "Rewrite the following text in a suspenseful, dramatic tone. Add tension and intrigue while keeping the core meaning. Use vivid, engaging language:",
        "Inspiring": "Rewrite the following text in an inspiring, motivational tone. Make it uplifting and encouraging while preserving the original message:"
    }

    prompt = f"""{tone_prompts[tone]}

Original Text: {original_text}

Rewritten Text:"""

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=1024)
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=512,
            temperature=0.7,
            top_p=0.9,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    rewritten = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Extract only the rewritten portion
    if "Rewritten Text:" in rewritten:
        rewritten = rewritten.split("Rewritten Text:")[-1].strip()
    else:
        # Fallback: take text after the original
        parts = rewritten.split(original_text)
        if len(parts) > 1:
            rewritten = parts[-1].strip()

    return rewritten

# ========================================
# 3. TEXT-TO-SPEECH FUNCTION
# ========================================
def generate_audio(text, voice):
    """Converts text to speech with voice selection"""

    # Map voice names to gTTS accents/languages for variety
    voice_map = {
        "Lisa (Female, Clear)": ("en", "com.au"),  # Australian English
        "Michael (Male, Deep)": ("en", "co.uk"),   # British English
        "Allison (Female, Warm)": ("en", "com")    # US English
    }

    lang, tld = voice_map.get(voice, ("en", "com"))

    # Generate audio
    tts = gTTS(text=text, lang=lang, tld=tld, slow=False)

    # Create temporary file
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    audio_file = f"audiobook_{timestamp}.mp3"
    tts.save(audio_file)

    return audio_file

# ========================================
# 4. MAIN PROCESSING FUNCTION
# ========================================
def process_audiobook(original_text, tone, voice):
    """Main function that orchestrates the entire pipeline"""

    if not original_text.strip():
        return "⚠️ Please enter some text to process.", "", None

    # Step 1: Rewrite text with selected tone
    status_msg = f"🔄 Rewriting text in {tone} tone..."
    print(status_msg)
    rewritten_text = rewrite_text(original_text, tone)

    # Step 2: Generate audio from rewritten text
    status_msg = f"🎙️ Generating {voice} narration..."
    print(status_msg)
    audio_file = generate_audio(rewritten_text, voice)

    # Step 3: Create comparison display
    comparison = f"""
### 📝 ORIGINAL TEXT
{original_text}

---

### ✨ {tone.upper()} TONE VERSION
{rewritten_text}
"""

    success_msg = f"✅ Audiobook generated successfully! Voice: {voice}"

    return success_msg, comparison, audio_file

# ========================================
# 5. GRADIO INTERFACE
# ========================================
def create_interface():
    """Creates the Gradio UI"""

    with gr.Blocks(title="🎧 Audiobook Generator", theme=gr.themes.Soft()) as app:

        gr.Markdown("""
        # 🎧 AI-Powered Audiobook Generator
        ### Transform your text with tone adaptation and natural voice narration

        **Features:**
        - 🎨 Tone-adaptive rewriting (Neutral, Suspenseful, Inspiring)
        - 🎙️ High-quality voice narration with multiple voices
        - 📊 Side-by-side text comparison
        - 💾 Downloadable MP3 audio files
        """)

        with gr.Row():
            with gr.Column(scale=2):
                input_text = gr.Textbox(
                    label="📝 Input Text",
                    placeholder="Enter or paste your text here...",
                    lines=8,
                    max_lines=15
                )

                with gr.Row():
                    tone_selector = gr.Radio(
                        choices=["Neutral", "Suspenseful", "Inspiring"],
                        label="🎨 Select Tone",
                        value="Neutral"
                    )

                    voice_selector = gr.Radio(
                        choices=[
                            "Lisa (Female, Clear)",
                            "Michael (Male, Deep)",
                            "Allison (Female, Warm)"
                        ],
                        label="🎙️ Select Voice",
                        value="Lisa (Female, Clear)"
                    )

                generate_btn = gr.Button("🎬 Generate Audiobook", variant="primary", size="lg")

        with gr.Row():
            status_output = gr.Textbox(label="📊 Status", lines=2)

        with gr.Row():
            comparison_output = gr.Markdown(label="📖 Text Comparison")

        with gr.Row():
            audio_output = gr.Audio(
                label="🎧 Generated Audiobook",
                type="filepath",
                interactive=False
            )

        # Example inputs
        gr.Markdown("### 💡 Try These Examples:")
        gr.Examples(
            examples=[
                [
                    "The old lighthouse stood alone on the rocky cliff. For decades, it had guided ships safely to shore. Now, it was just a memory of better times.",
                    "Suspenseful",
                    "Michael (Male, Deep)"
                ],
                [
                    "Every great achievement starts with a single step. Don't be afraid to begin your journey, even if the path seems unclear.",
                    "Inspiring",
                    "Allison (Female, Warm)"
                ],
                [
                    "The research study concluded that regular exercise improves both physical and mental health. Participants showed significant improvements.",
                    "Neutral",
                    "Lisa (Female, Clear)"
                ]
            ],
            inputs=[input_text, tone_selector, voice_selector]
        )

        # Connect the button to the processing function
        generate_btn.click(
            fn=process_audiobook,
            inputs=[input_text, tone_selector, voice_selector],
            outputs=[status_output, comparison_output, audio_output]
        )

        gr.Markdown("""
        ---
        ### 📋 How to Use:
        1. **Enter your text** in the input box
        2. **Choose a tone**: Neutral (objective), Suspenseful (dramatic), or Inspiring (motivational)
        3. **Select a voice**: Lisa, Michael, or Allison
        4. **Click Generate** and wait for your audiobook!
        5. **Listen and download** the MP3 file

        *Powered by IBM Granite 3.3 2B Instruct 🚀*
        """)

    return app

# ========================================
# 6. LAUNCH APPLICATION
# ========================================
print("\n" + "="*50)
print("🎧 AUDIOBOOK GENERATOR READY!")
print("="*50 + "\n")

app = create_interface()
app.launch(share=True, debug=False)